# Generated by Django 4.2.7 on 2025-10-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(max_length=64, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('related_alert_id', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
