# Generated by Django 4.2.7 on 2025-10-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(max_length=64, unique=True)),
                ('tenant_id', models.CharField(db_index=True, max_length=64)),
                ('timestamp', models.DateTimeField()),
                ('severity', models.CharField(max_length=16)),
                ('message', models.TextField()),
                ('source_index', models.CharField(max_length=64)),
            ],
        ),
    ]
